# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'Manny@sfangel.co'
  config.password       = 'h@67$27S'
  config.integrator_key = 'SFAN-21897a26-9108-43d1-b9b6-501d5b76e46a'
  config.account_id     = '341201'
  #config.endpoint       = 'https://www.docusign.net/restapi'
  #config.api_version    = 'v2'
end