# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'rake docusign_rest:generate_config' as many times as you need
# to replace the content of this file with a new config.

require 'docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'alexandr.larionov88@gmail.com'
  config.password       = 'alexandr9'
  config.integrator_key = 'ALEX-46557da2-175a-4662-9a7c-5abfe791c13c'
  config.account_id     = '1613988'
  #config.endpoint       = 'https://www.docusign.net/restapi'
  #config.api_version    = 'v1'
end

