module CampaignHelper

  def company_categories
    ["Advertising and Marketing",
    "Agriculture",
    "Art",
    "Biotechnology",
    "Business to Business",
    "Consumer Internet",
    "Consumer Products",
    "Data/Analytics",
    "Design",
    "E-Commerce",
    "Education",
    "Electronics",
    "Engineering",
    "Environment",
    "Events",
    "Fashion & Apparel",
    "Film & Video",
    "Financial Services",
    "Food & Beverage",
    "Gaming",
    "Government/Politics",
    "Health Tech",
    "Hospitality",
    "Legal Services",
    "Manufacturing",
    "Market Research",
    "Media",
    "Mobile",
    "Music",
    "Pharmaceutical",
    "Professional Services",
    "Publishing",
    "Retail",
    "Social Media",
    "Software & Services",
    "Sports",
    "Technology",
    "Transportation/Automotive",
    "Travel/Tourism"]
  end
end
